\timing

SELECT AVG(a), AVG(b) FROM test_parallel;

SELECT AVG(a), AVG(b) FROM test_parallel TABLESAMPLE BERNOULLI (1);
SELECT AVG(a), AVG(b) FROM test_parallel TABLESAMPLE BERNOULLI (10);
SELECT AVG(a), AVG(b) FROM test_parallel TABLESAMPLE BERNOULLI (20);
SELECT AVG(a), AVG(b) FROM test_parallel TABLESAMPLE BERNOULLI (30);
SELECT AVG(a), AVG(b) FROM test_parallel TABLESAMPLE BERNOULLI (40);
SELECT AVG(a), AVG(b) FROM test_parallel TABLESAMPLE BERNOULLI (50);
SELECT AVG(a), AVG(b) FROM test_parallel TABLESAMPLE BERNOULLI (60);
SELECT AVG(a), AVG(b) FROM test_parallel TABLESAMPLE BERNOULLI (70);
SELECT AVG(a), AVG(b) FROM test_parallel TABLESAMPLE BERNOULLI (80);
SELECT AVG(a), AVG(b) FROM test_parallel TABLESAMPLE BERNOULLI (90);
SELECT AVG(a), AVG(b) FROM test_parallel TABLESAMPLE BERNOULLI (100);

SELECT AVG(a), AVG(b) FROM test_parallel TABLESAMPLE SYSTEM (1);
SELECT AVG(a), AVG(b) FROM test_parallel TABLESAMPLE SYSTEM (10);
SELECT AVG(a), AVG(b) FROM test_parallel TABLESAMPLE SYSTEM (20);
SELECT AVG(a), AVG(b) FROM test_parallel TABLESAMPLE SYSTEM (30);
SELECT AVG(a), AVG(b) FROM test_parallel TABLESAMPLE SYSTEM (40);
SELECT AVG(a), AVG(b) FROM test_parallel TABLESAMPLE SYSTEM (50);
SELECT AVG(a), AVG(b) FROM test_parallel TABLESAMPLE SYSTEM (60);
SELECT AVG(a), AVG(b) FROM test_parallel TABLESAMPLE SYSTEM (70);
SELECT AVG(a), AVG(b) FROM test_parallel TABLESAMPLE SYSTEM (80);
SELECT AVG(a), AVG(b) FROM test_parallel TABLESAMPLE SYSTEM (90);
SELECT AVG(a), AVG(b) FROM test_parallel TABLESAMPLE SYSTEM (100);

